# Generated by Django 3.1.7 on 2021-02-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210220_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page ll', 'verbose_name_plural': 'Home Pages lls'},
        ),
    ]
